### ISSUE TITLE
Failure installing imagemagick by chocolatey on windows

### ISSUE THREAD

**Issue by axiom41** [IlfirinPL/robotframework-MarcinKoperski#17]
Hello.
After installing Chocolatey, i tried to install the imagemagick.tool, but the "choco install imagemagick.tool" command fails since it looks for versions "ImageMagick-7.1.0-**5**-portable-Q16-x86.zip" and "ImageMagick-7.1.0-**5**-portable-Q16-x64.zip", but they do not exist anymore (currently available portable version are "ImageMagick-7.1.0-**35**-portable-Q16-x86.zip" and "ImageMagick-7.1.0-**35**-portable-Q16-x64.zip").

Would it be possible to manually config imagemagick without using "choco" (best choice, even for future updates), or update the script with the currently available portable versions, or even use a local copy of imagemagick.tool to run the choco installation?

Many thanks in advance

**Comment by IlfirinPL** [comment]
Location and source is not impotent for imagemagick installation.
As long System Variable "MAGICK_HOME" contains path where binaries are located 
is example that add to system variables only set your location

`setx MAGICK_HOME "C:\ProgramData\chocolatey\lib\imagemagick.tool\tools"`

**Comment by IlfirinPL** [comment]
O i see now they remove convert and use magic instead command.  I will update this in future release for now you will have to use version 6.X

**Comment by axiom41** [comment]
Thank you, also for the advice on right version to use!

**Comment by IlfirinPL** [comment]
I remove all Image magic dependencies and choco, now use pure python
